name: Carga de la pagina
on: 
  config:
    branches:
      - main
jobs:
  deploy-page:
    runs-on: unbuntu-latest
    steps:
      name: Checkout
      uses: JamesIves/checkout@v2.3.1

      name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: public